import { icons } from "../constants";

export const DUMMY_DATA_ALL = [
  {
    icon: icons.gift,
    id: "1",
    heading: "Sell Gift Cards",
    price: "$1200",
    productId: "N1,681,530",
    date: "2:00 PM",
    text: "Valid bro, Your account has been credited..",
  },
  {
    icon: icons.gift,
    id: "2",
    heading: "Buy Gift Cards",
    price: "$800",
    productId: "N1,450,120",
    date: "3:15 PM",
    text: "Payment processed successfully.",
  },
  {
    icon: icons.bitCoin,
    id: "3",
    heading: "Sell Crypto",
    price: "$5000",
    productId: "N2,981,200",
    date: "1:45 PM",
    text: "Transaction confirmed on the blockchain.",
  },
  {
    icon: icons.bitCoin,
    id: "4",
    heading: "Buy Crypto",
    price: "$4500",
    productId: "N2,453,750",
    date: "4:30 PM",
    text: "Crypto has been added to your wallet.",
  },
  {
    icon: icons.gift,
    id: "5",
    heading: "Exchange Gift Cards",
    price: "$950",
    productId: "N1,305,890",
    date: "6:00 PM",
    text: "Exchange completed successfully.",
  },
  {
    icon: icons.gift,
    id: "6",
    heading: "Sell Amazon Cards",
    price: "$1100",
    productId: "N1,786,330",
    date: "11:00 AM",
    text: "Funds credited to your account.",
  },
  {
    icon: icons.bitCoin,
    id: "7",
    heading: "Sell Bitcoin",
    price: "$3200",
    productId: "N3,145,600",
    date: "12:30 PM",
    text: "Transaction validated on the blockchain.",
  },
  {
    icon: icons.bitCoin,
    id: "8",
    heading: "Buy Ethereum",
    price: "$2500",
    productId: "N2,650,400",
    date: "2:15 PM",
    text: "Ethereum added to your crypto wallet.",
  },
  {
    icon: icons.gift,
    id: "9",
    heading: "Buy Walmart Cards",
    price: "$700",
    productId: "N1,120,450",
    date: "10:00 AM",
    text: "Walmart cards have been purchased.",
  },
  {
    icon: icons.bitCoin,
    id: "10",
    heading: "Sell Litecoin",
    price: "$1400",
    productId: "N1,908,750",
    date: "3:50 PM",
    text: "Litecoin transaction successfully completed.",
  },
];

export const DUMMY_DATA_COMP = [
  {
    icon: icons.bitCoin,
    id: "3",
    heading: "Sell Crypto",
    price: "$5000",
    productId: "N2,981,200",
    date: "1:45 PM",
    text: "Transaction confirmed on the blockchain.",
  },
  {
    icon: icons.bitCoin,
    id: "4",
    heading: "Buy Crypto",
    price: "$4500",
    productId: "N2,453,750",
    date: "4:30 PM",
    text: "Crypto has been added to your wallet.",
  },
  {
    icon: icons.gift,
    id: "5",
    heading: "Exchange Gift Cards",
    price: "$950",
    productId: "N1,305,890",
    date: "6:00 PM",
    text: "Exchange completed successfully.",
  },
  {
    icon: icons.gift,
    id: "6",
    heading: "Sell Amazon Cards",
    price: "$1100",
    productId: "N1,786,330",
    date: "11:00 AM",
    text: "Funds credited to your account.",
  },
  {
    icon: icons.bitCoin,
    id: "7",
    heading: "Sell Bitcoin",
    price: "$3200",
    productId: "N3,145,600",
    date: "12:30 PM",
    text: "Transaction validated on the blockchain.",
  },
  {
    icon: icons.gift,
    id: "9",
    heading: "Buy Walmart Cards",
    price: "$700",
    productId: "N1,120,450",
    date: "10:00 AM",
    text: "Walmart cards have been purchased.",
  },
  {
    icon: icons.bitCoin,
    id: "10",
    heading: "Sell Litecoin",
    price: "$1400",
    productId: "N1,908,750",
    date: "3:50 PM",
    text: "Litecoin transaction successfully completed.",
  },
];

export const DUMMY_DATA_PROCESS = [
  {
    icon: icons.gift,
    id: "2",
    heading: "Buy Gift Cards",
    price: "$800",
    productId: "N1,450,120",
    date: "3:15 PM",
    text: "Payment processed successfully.",
  },
  {
    icon: icons.bitCoin,
    id: "3",
    heading: "Sell Crypto",
    price: "$5000",
    productId: "N2,981,200",
    date: "1:45 PM",
    text: "Transaction confirmed on the blockchain.",
  },
  {
    icon: icons.bitCoin,
    id: "4",
    heading: "Buy Crypto",
    price: "$4500",
    productId: "N2,453,750",
    date: "4:30 PM",
    text: "Crypto has been added to your wallet.",
  },
  {
    icon: icons.gift,
    id: "5",
    heading: "Exchange Gift Cards",
    price: "$950",
    productId: "N1,305,890",
    date: "6:00 PM",
    text: "Exchange completed successfully.",
  },
  {
    icon: icons.gift,
    id: "6",
    heading: "Sell Amazon Cards",
    price: "$1100",
    productId: "N1,786,330",
    date: "11:00 AM",
    text: "Funds credited to your account.",
  },
  {
    icon: icons.bitCoin,
    id: "10",
    heading: "Sell Litecoin",
    price: "$1400",
    productId: "N1,908,750",
    date: "3:50 PM",
    text: "Litecoin transaction successfully completed.",
  },
];

export const DUMMY_DATA_DECLINE = [
  {
    icon: icons.gift,
    id: "9",
    heading: "Buy Walmart Cards",
    price: "$700",
    productId: "N1,120,450",
    date: "10:00 AM",
    text: "Walmart cards have been purchased.",
  },
  {
    icon: icons.bitCoin,
    id: "10",
    heading: "Sell Litecoin",
    price: "$1400",
    productId: "N1,908,750",
    date: "3:50 PM",
    text: "Litecoin transaction successfully completed.",
  },
];
