import { icons } from "@/constants";

export const DUMMY_TRANS = [
  {
    icon: icons.gift,
    key: "1",
    heading: "Gift card solds",
    price: "$11000",
    productId: "N1,681,530",
    date: "11 Nov 2024",
    route: "/giftcardsold",
  },
  {
    icon: icons.gift,
    key: "2",
    heading: "Gift card bought",
    price: "$1200",
    productId: "N1,681,530",
    date: "2:00 PM",
    route: "/giftcardbought",
  },
  {
    icon: icons.bitCoin,
    key: "3",
    heading: "Crypto sold",
    price: "$1200",
    productId: "N1,681,530",
    date: "2:00 PM",
    route: "/cryptosold",
  },
  {
    icon: icons.bitCoin,
    key: "4",
    heading: "Crypto bought",
    price: "$1200",
    productId: "N1,681,530",
    date: "2:00 PM",
    route: "/cryptobought",
  },
];

export const DUMMY_GIFT_SOLDS_BOUGHT = [
  {
    icon: icons.gift,
    key: "1",
    heading: "Amazon",
    price: "$11000",
    productId: "N1,681,530",
    date: "11 Nov 2024",
  },
  {
    icon: icons.gift,
    key: "2",
    heading: "iTunes",
    price: "$1200",
    productId: "N1,681,531",
    date: "2:00 PM",
  },
  {
    icon: icons.gift,
    key: "3",
    heading: "Google Play",
    price: "$1200",
    productId: "N1,681,532",
    date: "2:00 PM",
  },
  {
    icon: icons.gift,
    key: "4",
    heading: "Amazon",
    price: "$1200",
    productId: "N1,681,533",
    date: "2:00 PM",
  },
  {
    icon: icons.gift,
    key: "5",
    heading: "iTunes",
    price: "$5000",
    productId: "N1,681,534",
    date: "9 Nov 2024",
  },
  {
    icon: icons.gift,
    key: "6",
    heading: "Google Play",
    price: "$700",
    productId: "N1,681,535",
    date: "1:30 PM",
  },
  {
    icon: icons.gift,
    key: "7",
    heading: "Amazon",
    price: "$150",
    productId: "N1,681,536",
    date: "10 Nov 2024",
  },
  {
    icon: icons.gift,
    key: "8",
    heading: "iTunes",
    price: "$300",
    productId: "N1,681,537",
    date: "3:45 PM",
  },
  {
    icon: icons.gift,
    key: "9",
    heading: "Google Play",
    price: "$900",
    productId: "N1,681,538",
    date: "6:00 PM",
  },
  {
    icon: icons.gift,
    key: "10",
    heading: "Amazon",
    price: "$3200",
    productId: "N1,681,539",
    date: "12:00 PM",
  },
];

export const DUMMY_CRYPTO_SOLDS_BOUGHT = [
  {
    icon: icons.bitCoin,
    key: "1",
    heading: "USDT",
    price: "$1200",
    productId: "N1,681,530",
    date: "2:00 PM",
  },
  {
    icon: icons.bitCoin,
    key: "2",
    heading: "Tron",
    price: "$1500",
    productId: "N1,681,531",
    date: "3:00 PM",
  },
  {
    icon: icons.bitCoin,
    key: "3",
    heading: "Shibu Inu",
    price: "$800",
    productId: "N1,681,532",
    date: "4:30 PM",
  },
  {
    icon: icons.bitCoin,
    key: "4",
    heading: "Bitcoin",
    price: "$500",
    productId: "N1,681,533",
    date: "5:15 PM",
  },
  {
    icon: icons.bitCoin,
    key: "5",
    heading: "USDT",
    price: "$400",
    productId: "N1,681,534",
    date: "6:00 PM",
  },
  {
    icon: icons.bitCoin,
    key: "6",
    heading: "Tron",
    price: "$2000",
    productId: "N1,681,535",
    date: "7:30 PM",
  },
  {
    icon: icons.bitCoin,
    key: "7",
    heading: "Shibu Inu",
    price: "$1000",
    productId: "N1,681,536",
    date: "8:45 PM",
  },
  {
    icon: icons.bitCoin,
    key: "8",
    heading: "Bitcoin",
    price: "$300",
    productId: "N1,681,537",
    date: "9:00 PM",
  },
  {
    icon: icons.bitCoin,
    key: "9",
    heading: "USDT",
    price: "$700",
    productId: "N1,681,538",
    date: "10:15 PM",
  },
  {
    icon: icons.bitCoin,
    key: "10",
    heading: "Tron",
    price: "$500",
    productId: "N1,681,539",
    date: "11:00 PM",
  },
];

export const COUNTRIES = [{ title: "Nigeria", id: 1 }];

export const GENDERS = [
  { id: 1, title: "male" },
  { id: 2, title: "female" },
  { id: 3, title: "other" },
];
